<?php

namespace ContainerCbnUSRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2Ne3c8pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2Ne3c8p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2Ne3c8p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conversacion' => ['privates', '.errored..service_locator.2Ne3c8p.App\\Entity\\Conversacion', NULL, 'Cannot autowire service ".service_locator.2Ne3c8p": it needs an instance of "App\\Entity\\Conversacion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'conversacion' => 'App\\Entity\\Conversacion',
        ]);
    }
}
