<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerArk5bm4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerArk5bm4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerArk5bm4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerArk5bm4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerArk5bm4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ark5bm4',
    'container.build_id' => 'f4b4197a',
    'container.build_time' => 1717257336,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerArk5bm4');
