<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXi6gouk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXi6gouk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXi6gouk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXi6gouk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXi6gouk\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xi6gouk',
    'container.build_id' => 'c5ddd418',
    'container.build_time' => 1715786804,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXi6gouk');
