<?php

namespace ContainerJ2fQ5qK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FBaCfmjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FBaCfmj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FBaCfmj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'temasModule' => ['privates', 'App\\Module\\TemasModule', 'getTemasModuleService', true],
        ], [
            'temasModule' => 'App\\Module\\TemasModule',
        ]);
    }
}
