<?php

namespace ContainerJ2fQ5qK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_THbmHY5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.THbmHY5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.THbmHY5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoriaModule' => ['privates', 'App\\Module\\CategoriaModule', 'getCategoriaModuleService', true],
            'escalaRepository' => ['privates', 'App\\Repository\\EscalaRepository', 'getEscalaRepositoryService', true],
            'productoImagenModule' => ['privates', 'App\\Module\\ProductoImagenModule', 'getProductoImagenModuleService', true],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
        ], [
            'categoriaModule' => 'App\\Module\\CategoriaModule',
            'escalaRepository' => 'App\\Repository\\EscalaRepository',
            'productoImagenModule' => 'App\\Module\\ProductoImagenModule',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
        ]);
    }
}
