<?php

namespace ContainerJ2fQ5qK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MUSGIxdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MUSGIxd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MUSGIxd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'lineaPedidoRepository' => ['privates', 'App\\Repository\\LineaPedidoRepository', 'getLineaPedidoRepositoryService', true],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
        ], [
            'entityManager' => '?',
            'lineaPedidoRepository' => 'App\\Repository\\LineaPedidoRepository',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
        ]);
    }
}
