<?php

namespace ContainerJ2fQ5qK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6WfvakeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6Wfvake' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6Wfvake'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'categoriaModule' => ['privates', 'App\\Module\\CategoriaModule', 'getCategoriaModuleService', true],
        ], [
            'authenticationUtils' => '?',
            'categoriaModule' => 'App\\Module\\CategoriaModule',
        ]);
    }
}
