<?php

namespace ContainerJ2fQ5qK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemasModuleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Module\TemasModule' shared autowired service.
     *
     * @return \App\Module\TemasModule
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Module/TemasModule.php';

        return $container->privates['App\\Module\\TemasModule'] = new \App\Module\TemasModule(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
