<?php

namespace ContainerXi6gouk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMensajeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MensajeController' shared autowired service.
     *
     * @return \App\Controller\MensajeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MensajeController.php';

        $container->services['App\\Controller\\MensajeController'] = $instance = new \App\Controller\MensajeController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\MensajeRepository'] ?? $container->load('getMensajeRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\MensajeController', $container));

        return $instance;
    }
}
