<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \App\Entity\Producto implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'equipo' => [parent::class, 'equipo', null],
        "\0".parent::class."\0".'escala' => [parent::class, 'escala', null],
        "\0".parent::class."\0".'fabricante' => [parent::class, 'fabricante', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imagenes' => [parent::class, 'imagenes', null],
        "\0".parent::class."\0".'lineaPedidos' => [parent::class, 'lineaPedidos', null],
        "\0".parent::class."\0".'listaDeseos' => [parent::class, 'listaDeseos', null],
        "\0".parent::class."\0".'nombre_producto' => [parent::class, 'nombre_producto', null],
        "\0".parent::class."\0".'precio' => [parent::class, 'precio', null],
        "\0".parent::class."\0".'segunda_mano' => [parent::class, 'segunda_mano', null],
        "\0".parent::class."\0".'stock' => [parent::class, 'stock', null],
        "\0".parent::class."\0".'valoraciones' => [parent::class, 'valoraciones', null],
        'equipo' => [parent::class, 'equipo', null],
        'escala' => [parent::class, 'escala', null],
        'fabricante' => [parent::class, 'fabricante', null],
        'id' => [parent::class, 'id', null],
        'imagenes' => [parent::class, 'imagenes', null],
        'lineaPedidos' => [parent::class, 'lineaPedidos', null],
        'listaDeseos' => [parent::class, 'listaDeseos', null],
        'nombre_producto' => [parent::class, 'nombre_producto', null],
        'precio' => [parent::class, 'precio', null],
        'segunda_mano' => [parent::class, 'segunda_mano', null],
        'stock' => [parent::class, 'stock', null],
        'valoraciones' => [parent::class, 'valoraciones', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
