<?php

namespace ContainerLwsxNTl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConversacionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ConversacionController' shared autowired service.
     *
     * @return \App\Controller\ConversacionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ConversacionController.php';

        $container->services['App\\Controller\\ConversacionController'] = $instance = new \App\Controller\ConversacionController(($container->privates['App\\Repository\\UsuarioRepository'] ?? $container->load('getUsuarioRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\ConversacionRepository'] ?? $container->load('getConversacionRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\ConversacionController', $container));

        return $instance;
    }
}
