<?php

namespace ContainerLwsxNTl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConversacionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2Ne3c8p.App\Entity\Conversacion' shared service.
     *
     * @return \App\Entity\Conversacion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2Ne3c8p": it needs an instance of "App\\Entity\\Conversacion" but this type has been excluded in "config/services.yaml".');
    }
}
