<?php

namespace ContainerXxgnqiT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriaModuleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Module\CategoriaModule' shared autowired service.
     *
     * @return \App\Module\CategoriaModule
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Module/CategoriaModule.php';

        return $container->privates['App\\Module\\CategoriaModule'] = new \App\Module\CategoriaModule(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
