<?php

namespace ContainerKzuTug3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M_W9kDlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M.W9kDl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M.W9kDl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoriaModule' => ['privates', 'App\\Module\\CategoriaModule', 'getCategoriaModuleService', true],
            'lineaPedidoRepository' => ['privates', 'App\\Repository\\LineaPedidoRepository', 'getLineaPedidoRepositoryService', true],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
            'valoracionRepository' => ['privates', 'App\\Repository\\ValoracionRepository', 'getValoracionRepositoryService', true],
        ], [
            'categoriaModule' => 'App\\Module\\CategoriaModule',
            'lineaPedidoRepository' => 'App\\Repository\\LineaPedidoRepository',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
            'valoracionRepository' => 'App\\Repository\\ValoracionRepository',
        ]);
    }
}
