<?php

namespace ContainerVYaLtsZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductoImagenModuleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Module\ProductoImagenModule' shared autowired service.
     *
     * @return \App\Module\ProductoImagenModule
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Module/ProductoImagenModule.php';

        return $container->privates['App\\Module\\ProductoImagenModule'] = new \App\Module\ProductoImagenModule();
    }
}
