<?php

namespace Container6h14Z64;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IRZ7ziLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IRZ7ziL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IRZ7ziL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoriaModuCategoriaModule' => ['privates', 'App\\Module\\CategoriaModule', 'getCategoriaModuleService', true],
            'metodoDePagoRepository' => ['privates', 'App\\Repository\\MetodoDePagoRepository', 'getMetodoDePagoRepositoryService', true],
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
        ], [
            'categoriaModuCategoriaModule' => 'App\\Module\\CategoriaModule',
            'metodoDePagoRepository' => 'App\\Repository\\MetodoDePagoRepository',
            'productoRepository' => 'App\\Repository\\ProductoRepository',
        ]);
    }
}
